# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 199993dad10c5a304b5cfe7e917f7a97d729a8643d0e1b31fd67c9a2a7adfed482ea3d5d053ae9b716be8861124a04d574ff197428e31698d8dd65f5fafe5c3e

test:
  secret_key_base: 23a15476e8fb80f710a70962f9f7bdc74702f5e460ba747c61efc8b4d140997fe64413daae1a6ca681da7feac29a9950e5b4be0112b94fbb7879958095afa4fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
